FROM node:alpine
LABEL maintainer="julio@blackdevs.com.br"

WORKDIR /app
COPY ./swagger-docs /app
RUN npm install

EXPOSE 8000

ENTRYPOINT [ "npm", "start" ]

# docker image build --tag juliocesarmidia/ipv6-converter-docs -f Dockerfile-docs .
# docker container run -d --name ipv6-converter-docs -p 8000:8000 juliocesarmidia/ipv6-converter-docs